// Code generated by github.com/alanctgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     foo.avsc
 */

package events

type UnionStringNull struct {
	String    string
	Null      interface{}
	UnionType UnionStringNullTypeEnum
}

type UnionStringNullTypeEnum int

const (
	UnionStringNullTypeEnumString UnionStringNullTypeEnum = 0
	UnionStringNullTypeEnumNull   UnionStringNullTypeEnum = 1
)
